name: GitHub Actions Demo
on: [push]
jobs:
  ROS2-tests:
    runs-on: self-hosted
    container: osrf/ros:galactic-desktop
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Create Colcon WS
        run:
          mkdir $GITHUB_WORKSPACE/aerostack_ws/src -p ;
          cd $GITHUB_WORKSPACE/aerostack_ws/src ;
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: echo $(pwd) && ls .
      - run: echo "ğŸ This job's status is ${{ job.status }}."
